MOD_ALT = 0x0001
MOD_CONTROL = 0x0002
MOD_SHIFT = 0x0004
MOD_WIN = 0x0008
MOD_NOREPEAT = 0x4000
WM_HOTKEY = 0x0312
WM_QUIT = 0x0012
HOTKEY_ID = 1

APP_VERSION = "1.1.0"
APP_NAME = "CVInput"

DEFAULT_HOTKEY = "Ctrl+V"
DEFAULT_INTERVAL = 0.03
DEFAULT_AUTO_CLIPBOARD = True
DEFAULT_ALWAYS_ON_TOP = True
DEFAULT_CLEAR_AFTER_INPUT = False
DEFAULT_CLOSE_TO_TRAY = False
DEFAULT_STARTUP_ON_BOOT = False
DEFAULT_OPACITY = 1.0
DEFAULT_LANGUAGE = "zh_cn"

DEFAULT_CONFIG = {
    "hotkey": DEFAULT_HOTKEY,
    "interval": DEFAULT_INTERVAL,
    "always_on_top": DEFAULT_ALWAYS_ON_TOP,
    "auto_clipboard": DEFAULT_AUTO_CLIPBOARD,
    "clear_after_input": DEFAULT_CLEAR_AFTER_INPUT,
    "close_to_tray": DEFAULT_CLOSE_TO_TRAY,
    "startup_on_boot": DEFAULT_STARTUP_ON_BOOT,
    "opacity": DEFAULT_OPACITY,
    "language": DEFAULT_LANGUAGE,
}
