MOD_ALT = 0x0001
MOD_CONTROL = 0x0002
MOD_SHIFT = 0x0004
MOD_WIN = 0x0008
MOD_NOREPEAT = 0x4000
WM_HOTKEY = 0x0312
WM_QUIT = 0x0012
HOTKEY_ID = 1

APP_VERSION = "1.1.0"
APP_NAME = "CVI"

DEFAULT_HOTKEY = "Ctrl+V"
DEFAULT_INTERVAL_MS = 30
DEFAULT_AUTO_CLIPBOARD = True
DEFAULT_ALWAYS_ON_TOP = True
DEFAULT_CLEAR_AFTER_INPUT = False
DEFAULT_DISABLE_HOTKEY_WHEN_CLIPBOARD_EMPTY = True
DEFAULT_TOGGLE_IME_WITH_SHIFT = True
DEFAULT_NEWLINE_WITH_SHIFT_ENTER = True
DEFAULT_MULTI_SLOT_ENABLED = True
DEFAULT_MULTI_SLOTS = [""] * 10
DEFAULT_CLOSE_TO_TRAY = True
DEFAULT_STARTUP_ON_BOOT = False
DEFAULT_OPACITY = 1.0
DEFAULT_LANGUAGE = "zh_cn"
DEFAULT_REMEMBER_SETTINGS = True
DEFAULT_CLOSE_POPUP_ON_BLUR = True
DEFAULT_CUSTOM_INTERVAL_ENABLED = False

DEFAULT_CONFIG = {
    "hotkey": DEFAULT_HOTKEY,
    "interval_ms": DEFAULT_INTERVAL_MS,
    "always_on_top": DEFAULT_ALWAYS_ON_TOP,
    "auto_clipboard": DEFAULT_AUTO_CLIPBOARD,
    "clear_after_input": DEFAULT_CLEAR_AFTER_INPUT,
    "disable_hotkey_when_clipboard_empty": DEFAULT_DISABLE_HOTKEY_WHEN_CLIPBOARD_EMPTY,
    "toggle_ime_with_shift": DEFAULT_TOGGLE_IME_WITH_SHIFT,
    "newline_with_shift_enter": DEFAULT_NEWLINE_WITH_SHIFT_ENTER,
    "multi_slot_enabled": DEFAULT_MULTI_SLOT_ENABLED,
    "multi_slots": list(DEFAULT_MULTI_SLOTS),
    "close_to_tray": DEFAULT_CLOSE_TO_TRAY,
    "startup_on_boot": DEFAULT_STARTUP_ON_BOOT,
    "opacity": DEFAULT_OPACITY,
    "language": DEFAULT_LANGUAGE,
    "remember_settings": DEFAULT_REMEMBER_SETTINGS,
    "close_popup_on_blur": DEFAULT_CLOSE_POPUP_ON_BLUR,
    "custom_interval_enabled": DEFAULT_CUSTOM_INTERVAL_ENABLED,
}
